version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    restart: always
    networks:
      - frontend
    ports:
      - "443:443"
    volumes:
      - ./volumes/ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  teampass:
    image: teampass/teampass
    restart: always
    environment:
      VIRTUAL_HOST: teampass.example.com
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/teampass:/var/www/html
    ports:
      - "8088:80"

  db:
    restart: always
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - backend
    ports:
      - "13306:3306"

networks:
  frontend:
  backend:
